### ISSUE TITLE
Remove outdated/obsolete anti pattern 2

### ISSUE THREAD

**Issue by danieldeleo** [GoogleCloudPlatform/bigquery-antipattern-recognition#12]
Regarding "Anti Pattern 2: Using CROSS JOINs when INNER JOINs are an option", BigQuery now optimizes this into an inner join automatically. Recommend removing from the tool and docs

**Comment by franklinWhaite** [comment]
Thanks for bringing this up.
That anti pattern is actually deprecated in the code since a while ago, we had not updated the readme, we have create a [PR](https://github.com/GoogleCloudPlatform/bigquery-antipattern-recognition/pull/21) to fix this.

**Comment by franklinWhaite** [comment]
Readme updated
