### ISSUE TITLE
antipattern analysis output not loaded to BQ output table

### ISSUE THREAD

**Issue by apoorvawathodkar** [GoogleCloudPlatform/bigquery-antipattern-recognition#5]
While executing the antipattern analysis, I am seeing the following behaviour:

- when using input as information schema and output as a bq table, the output is not loaded to the table. I do see in the console log that it recognizes a few queries with anti-patterns, however, nothing is logged in the output table.
![image](https://github.com/GoogleCloudPlatform/bigquery-antipattern-recognition/assets/72031005/d539af2b-c823-446b-847b-4850bd731bc9)

- When I try using --output_file_path instead of --output_table, the analysis itself changes and no output file is created.
![image](https://github.com/GoogleCloudPlatform/bigquery-antipattern-recognition/assets/72031005/d47884e0-dbd3-49d5-b990-78a2607b0bf8)

In the above two cases, only the output mode was changed. None of the options produced the output.
Also, option 1 recognized 2 queries with anti-patterns whereas option 2 did not.

Trying to understand what could be the issue here. 
Any help is much appreciated.

**Comment by franklinWhaite** [comment]
Fixed with https://github.com/GoogleCloudPlatform/bigquery-antipattern-recognition/pull/7
